### ISSUE TITLE
When viewing item, it doesn't reflect on control

### ISSUE THREAD

**Issue by ianblair44** [deepakshrma/peoplePlugin#26]
When viewing an item, it should reflect the items control on the left hand side. 

Also the image is not like the mockup. 

![screen shot 2015-08-05 at 10 01 39 am](https://cloud.githubusercontent.com/assets/2794086/9092120/f9e899e0-3b58-11e5-89bd-c834c507cb4e.png)

**Comment by sakshityagi** [comment]
Had a discussion with Daniel regarding this. He will look into it and provide us some event and trigger methods to handle this.

**Comment by sakshityagi** [comment]
Use : https://github.com/BuildFire/sdk/wiki/How-to-use-Messaging-to-sync-your-Control-to-Widget

**Comment by sakshityagi** [comment]
Done. Should be working now.

**Comment by deepakshrma** [comment]
It is not working for first time. If user has not selected any layout, use any default layout in that case.
Or you can check, If there is no layout field create/save default layout for user on bootstrapping time.
![layout issue](https://cloud.githubusercontent.com/assets/7682731/9243774/48c35a96-41b2-11e5-8c33-bf099dc6c958.png)

**Comment by sakshityagi** [comment]
Fixed please review.

**Comment by deepakshrma** [comment]
@sakshityagi Still not working.. new issue :-1: 
![zdsdsd](https://cloud.githubusercontent.com/assets/7682731/9257136/865af008-4211-11e5-93ed-b84146567d3f.png)
